name: phishing-detector
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-learn
  - flask
  - flask-cors
  - joblib
  - jupyterlab  # optional, for experimentation
