[build]
builder = "python"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300

[deploy.envs]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
